### ISSUE TITLE
3D hardware acceleration?

### ISSUE THREAD

**Issue by kenderipa** [ivan-hc/ArchImage#20] opened 2024-03-18 07:29 UTC
Hello again,

I'm trying to build a Lutris AppImage. After building and l;aunching, it has following output:

`Vulkan is not available or your system isn't Vulkan capable`

Vulkan is, of course, installed on my system. How do I expose it for the AppImage (it probably tries to call vulkaninfo).

**Comment by ivan-hc** [comment] 2024-03-18 14:00
Hi, this is a (sad) known issue... and a work in progress, see https://github.com/fsquillace/junest/issues/344

Latelly I discovered that by installing `libselinux` (from AUR, in the AppImage... you need to enable $BASICSTUFF, $COMPILERS and the AUR key) and by adding the following line into the AppRun (before "EXEC=")...
```
LD_LIBRARY_PATH=/lib/:/lib64/:/lib/x86_64-linux-gnu/:/usr/lib/:"${LD_LIBRARY_PATH}"' >> ./$APP/$APP.AppDir/AppRun
```
something changes in the output messages.

However, I've not done furter experiments about this.

Would you try by yourself?

**Comment by ivan-hc** [comment] 2024-03-18 14:18
Right now I've tried to build SuperTuxKart by adding libselinux in "DEPENDENCES" and the line above in the AppRun, this is the message I have:
```
..:: Antarctica Rendering Engine 2.0 ::..
[info   ] [IrrDriver Logger]: ..:: Antarctica Rendering Engine 2.0 ::..
[info   ] [IrrDriver Logger]: Could not initialize display!
[info   ] [IrrDriver Logger]: ..:: Antarctica Rendering Engine 2.0 ::..
[info   ] [IrrDriver Logger]: Could not initialize display!
[info   ] [IrrDriver Logger]: ..:: Antarctica Rendering Engine 2.0 ::..
[info   ] [IrrDriver Logger]: Could not initialize display!
[info   ] [IrrDriver Logger]: ..:: Antarctica Rendering Engine 2.0 ::..
[info   ] [IrrDriver Logger]: Could not initialize display!
[fatal  ] irr_driver: Couldn't initialise irrlicht device. Quitting.
```

**Comment by ivan-hc** [comment] 2024-03-18 14:21
NOTE: without "libselinux" installed into the AppImage, exporting LD_LIBRARY_PATH is useless and destructive... the AppImage would not run at all. In some way, "libselinux" helps to run both the libraries from the AppImage and from the host.

**Comment by ivan-hc** [comment] 2024-03-18 14:44
UPDATE: also "libOpenGL libEGL libGLdispatch" must be included in "LIBSAVED="

**Comment by ivan-hc** [comment] 2024-03-18 14:55
UPDATE: I've included also "libX11.so" in "LIBSAVED=" and I have several errors like this
```
/lib/libX11.so.6: error: symbol lookup error: undefined symbol: _XIFreeDeviceInfo (fatal)
```
I can't see the bottom, the messages are too long for my terminal

**Comment by ivan-hc** [comment] 2024-03-18 15:31
UPDATE: in first I've included all libraries in /usr/lib, the game starts but not the gameplay

Then I've execute directly the whole JuNest without removals... same result.

So, I think that here the issue is to use "--bind" to let the AppImage use libraries from the host... or at least LD_PRELOAD

If you want to test this, I'll resume the lines you must change in the script:

- Line 6, "DEPENDENCES=" must include "libselinux"
- Uncomment lines 7 and 8 (i.e. BASICSTUFF and COMPILERS
- Uncomment line 69 (to enable `gpg --keyserver keyserver.ubuntu.com ...`, needed for the AUR)
- Do "ENTER" at line 90 and add the following line: `export LD_LIBRARY_PATH=/lib/:/lib64/:/lib/x86_64-linux-gnu/:/usr/lib/:"${LD_LIBRARY_PATH}"`
- Line 234 (former line 233, see the step above), "LIBSAVED=" must include `libOpenGL libEGL libGLdispatch libX`

From here, I can't see furter improvements.

I hope you are luckier. Have fun.

**Comment by ivan-hc** [comment] 2024-03-19 19:59
@kenderipa see https://github.com/ivan-hc/ArchImage/commit/fa7c6f698e4efc1b746ad1c9a14560491731054a

From now all you need is:
- Line 6, "DEPENDENCES=" must include "`libselinux`"
- Line 243, "LIBSAVED=" must include `libOpenGL libEGL libGLdispatch libX` ...

all our tests can be done like this.

**Comment by ivan-hc** [comment] 2024-03-21 03:49
In the meantime the AppImages are Type3: no `libfuse2` is needed on the host

**Comment by kenderipa** [comment] 2024-03-21 19:18
Interestingly, 3D acceleration works for ScummVm out of the box.

**Comment by ivan-hc** [comment] 2024-03-21 19:26
Does ScummVm requiring GL accelleration?

I know that 32bit games in WINE work quite well, also without these implementations. Maybe you're wrong.

**Comment by kenderipa** [comment] 2024-03-21 19:31
> Does ScummVm requiring GL accelleration?
> 
> I know that 32bit games in WINE work quite well, also without these implementations. Maybe you're wrong.

That I may be, but I'm pretty sure that Longest Journey, a 3D game, with an enhanced texture pack requires at least OpenGL. Also, I can switch on OpenGL for ScummVM GUI. Only v-sync doesn't seem to work.

**Comment by ivan-hc** [comment] 2024-03-21 19:35
What GPU? I've an old Nvidia (so I'm pretty sure that it would not work for me out of the box)

**Comment by kenderipa** [comment] 2024-03-21 20:38
> What GPU? I've an old Nvidia (so I'm pretty sure that it would not work for me out of the box)

1660 Ti

**Comment by ivan-hc** [comment] 2024-03-21 20:39
Can you do a test with SuperTuxKart?

**Comment by kenderipa** [comment] 2024-03-21 21:02
> Can you do a test with SuperTuxKart?

Sure, in the next few days.

**Comment by ivan-hc** [comment] 2024-03-22 01:45
Steps I've done (for `supertuxkart`)

- add `libselinux` in dependences
- add `GL libX` in "LIBSAVED"
- enable `_include_swrast_dri`

No audio, no gameplay... just menus and loading screen

**Comment by kenderipa** [comment] 2024-03-22 09:14
So, Supertuxkart doesn't work for me, I have an endless lading screen.

**Comment by ivan-hc** [comment] 2024-03-24 05:00
@kenderipa maybe you're right. Maybe there is an issue only with SupertuxKart (we miss something in the bundle).

I've built the old car race game Torcs and works! I'll publish the new repo soon (just the time to fix missing audio issue).

**Comment by kenderipa** [comment] 2024-03-24 09:49
> @kenderipa maybe you're right. Maybe there is an issue only with SupertuxKart (we miss something in the bundle).
> 
> I've built the old car race game Torcs and works! I'll publish the new repo soon (just the time to fix missing audio issue).
> 

I've built Astromenace and 0 A. D., they both run very slowly, about 5-10 FPS.

**Comment by ivan-hc** [comment] 2024-03-24 19:13
> I've built Astromenace and 0 A. D., they both run very slowly, about 5-10 FPS.

you should run them using `LD_DEBUG=libs`

**Comment by ivan-hc** [comment] 2024-03-24 21:18
@kenderipa I've tried to install 0ad and got this error
```
WARNING: You are using 'llvmpipe (LLVM 17.0.6, 256 bits)' graphics driver, expect very poor performance!
```
I've done a search and found this https://wiki.archlinux.org/title/OpenGL

**Comment by ivan-hc** [comment] 2024-03-25 00:32
This is the script I wrote for "0AD" [0ad-junest.txt](https://github.com/ivan-hc/ArchImage/files/14737370/0ad-junest.txt) (I had to rename it to .txt file because github does not allow .sh formats)

@andy5995 I'd like to have you in this Team, you're the expert of drivers support for this game

If you already had experienced with Archimages, all you have to do is to run the script I wrote to have a 1,8 GB AppImage of the "0AD" game, but we have an issue here to made it work with the host's drivers (being Archimage a Arch Linux container into an AppImage... we are trying to made it use the drivers of the host system).

**Comment by andy5995** [comment] 2024-03-25 10:12
@ivan-hc I'm no expert regarding the drivers but thank you for the compliment.

The way I worked around this [with the 0ad AppImage](https://github.com/0ad-matters/0ad-appimage/issues/19#issuecomment-1595984082) was build one using Ubuntu 22.04 (Jammy). With no changes to how I built the AppImage, the image detected Vulkan whereas the image built on Ubuntu 20.04 (focal) did not (see the link above for more details).

**Comment by ivan-hc** [comment] 2024-03-25 10:36
@andy5995 sure, I remember this detail about the two different versions of Ubuntu.

In this case, Archimages are able to work also on old dritributions with at least the Linux kernel v2.6 (so distributions of 10 years ago or more).

The only thing this kind of packaging lacks is support for GPU accelleration, due to its container's nature.

However, to include the changes we are discovering in this issue, we are near to a solution.

In this example, 0ad runs and works but with a very low performaces and about 5-10 FPS... we have this message in the terminal (and on the UI):
```
WARNING: You are using 'llvmpipe (LLVM 17.0.6, 256 bits)' graphics driver, expect very poor performance!
```

Now, two would be the solutions:
- on the Bublewrap side (needed to run the JuNest container inside the AppImage) whe have to use "--bind" to made a host's directory available into the container (this will overwrite the files in that path inside the AppImage and the app may not work as expected if we do something wrong);
- alternativelly we have to "export" the correct variables. For example, we here have already exported "LD_LIBRARY_PATH" from the host to the AppImage... this is OK to made available some missing libraries... but what about MESA? VULKAN? Other GL* related variables?

Now, the responsible of the drivers is "libLLVM-17.so" in /usr/lib (into the AppImage) that asks for "swrast_dri.so" in /usr/lib/dri (always inside the AppImage).

We need a way to use our drivers on the host instead of let the AppImage rely on what its bundled into it.

**Comment by ivan-hc** [comment] 2024-06-24 14:54
Just experienced that this issue only affects systems with proprietary Nvidia drivers, I've tried this in some Kde games at https://github.com/ivan-hc/KDE-games-suite-appimage/issues/3 and in a pure Archimage-based Bottles version (not the hybrid one I've published, mixing Arch Linux + Debian).

3D gamse will work with Nouveau enabled, not with Nvidia propriatary drivers.

**Comment by ivan-hc** [comment] 2024-06-24 16:42
@kenderipa how can I force an app using "nouveau" drivers instead of "nvidia"?

**Comment by kenderipa** [comment] 2024-06-24 19:52
> @kenderipa how can I force an app using "nouveau" drivers instead of "nvidia"?

No idea. You can, of course, deinstall the nVidia drivers and reinstall them again.

**Comment by ivan-hc** [comment] 2024-06-24 20:00
> > @kenderipa how can I force an app using "nouveau" drivers instead of "nvidia"?
> 
> No idea. You can, of course, uninstall the nVidia drivers and reinstall them again.

its not a solution, but a workaroun... like the one I proposed.

No progresses in these months on this issue.

**Comment by Samueru-sama** [comment] 2024-06-24 22:52
aisap binds the following to allow access to the GPU, maybe one of these is missing? 

```
/sys/devices/pci000:00
/dev/nvidiactl
/dev/nvidia0
```

**Comment by qurious-pixel** [comment] 2024-07-16 19:49
I was also trying to work this out, as this was the last thing I was stuck on, specifically for OBS using nVidia hardware acceleration. I had tested some theories, but they did not work out in the end. Back to the beginning.

**Comment by ivan-hc** [comment] 2024-07-16 20:02
@qurious-pixel JuNest, and Archimages in general, use theiir internal copy of Bubblewrap to mount directories from the host system.

This is how the AppRun works in the latest version of my Archimages:
```
#!/bin/sh
HERE="$(dirname "$(readlink -f $0)")"
export UNION_PRELOAD=$HERE
export JUNEST_HOME=$HERE/.junest
export PATH=$PATH:$HERE/.local/share/junest/bin

if test -f /etc/resolv.conf; then ETC_RESOLV=' --bind /etc/resolv.conf /etc/resolv.conf '; fi
if test -d /media; then MNT_MEDIA_DIR=' --bind /media /media '; fi
if test -d /mnt; then MNT_DIR=' --bind /mnt /mnt '; fi
if test -d /opt; then OPT_DIR=' --bind /opt /opt '; fi
if test -d /run/user; then USR_LIB_LOCALE_DIR=' --bind /usr/lib/locale /usr/lib/locale '; fi
if test -d /usr/share/fonts; then USR_SHARE_FONTS_DIR=' --bind /usr/share/fonts /usr/share/fonts '; fi
if test -d /usr/share/themes; then USR_SHARE_THEMES_DIR=' --bind /usr/share/themes /usr/share/themes '; fi

BINDS=" $ETC_RESOLV $MNT_MEDIA_DIR $MNT_DIR $OPT_DIR $USR_LIB_LOCALE_DIR $USR_SHARE_FONTS_DIR $USR_SHARE_THEMES_DIR "

if test -f $JUNEST_HOME/usr/lib/libselinux.so; then export LD_LIBRARY_PATH=/lib/:/lib64/:/lib/x86_64-linux-gnu/:/usr/lib/:"${LD_LIBRARY_PATH}"; fi

EXEC=$(grep -e '^Exec=.*' "${HERE}"/*.desktop | head -n 1 | cut -d "=" -f 2- | sed -e 's|%.||g')
$HERE/.local/share/junest/bin/junest -n -b "$BINDS" -- $EXEC "$@"
```
where "$BINDS" are all mountpoints.

For example, "$USR_SHARE_THEMES_DIR" is ` --bind /usr/share/themes /usr/share/themes `, in a normal JuNest installation it would appear like this, to launch (for example) "obs"
```
junest -n -b " --bind /usr/share/themes /usr/share/themes " -- obs
```
with this command you use "junest" to launch "obs", and the internal Bubblewrap "-b" mounts the "/usr/share/themes" of the host in the guest Arch Linux container.

The directory "/usr/share/themes" must exist in both, host and guest.

Once we mount the exact files and directories from the host into the guest, we solve this issue.

But as you can see, this is an issue opened from months, without significative progresses.

**Comment by ivan-hc** [comment] 2024-12-27 22:04
After several months I finally found a solution. I use also another project named Conty, when I run a container from that project, it creates Nvidia drivers locally, undes $HOME/.local/share/Conty. By adding these lines in the AppRun
```
export DATADIR="${XDG_DATA_HOME:-$HOME/.local/share}"
export PATH=$PATH:$DATADIR/Conty/overlayfs_shared/up/usr/bin:${PATH}
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$DATADIR/Conty/overlayfs_shared/up/usr/lib:${LD_LIBRARY_PATH}
export XDG_DATA_DIRS=$XDG_DATA_DIRS:$DATADIR/Conty/overlayfs_shared/up/usr/share:${XDG_DATA_DIRS}
```
all Archimages have hardware accelleration!

I'd like to port [this solution](https://github.com/Kron4ek/Conty/blob/master/conty-start.sh#L392) into a script, so we can syntetize it even more to compile Nvidia drivers locally. I'm already able to detect my Nvidia version, download and extract the oficial Nvidia driver... but I'm unable to compile it into a rootless directory.

Btw this issue finally comes to an end. It won't take long.

**Comment by ivan-hc** [comment] 2024-12-28 08:01
First test is a success. Try my Archimage of Hypnotix

https://github.com/ivan-hc/Hypnotix-appimage/releases/tag/continuous

as always, the first start will run Conty to create the local Nvidia drivers.

I'd like to made this quickier.

**Comment by ivan-hc** [comment] 2024-12-28 08:02
Closed by mistake. Sorry.

**Closed** 2024-12-29 00:58 UTC
Labels: help wanted, good first issue

**Comment by ivan-hc** [comment] 2024-12-29 01:27
This time its not a mistake

https://github.com/user-attachments/assets/782dd318-8176-471d-ade2-df2a660e21fc

https://github.com/ivan-hc/ArchImage/commit/a8fae45af23153cae42c3a4f2533165ec30aef31

https://github.com/ivan-hc/ArchImage/#hardware-acceleration

Any improvement is wellcome.

**Comment by ivan-hc** [comment] 2024-12-30 02:27
@andy5995 I play with your 0AD AppImage almost every day, but I built one based on Archimage right today that you should take a look at

- script https://github.com/ivan-hc/My-workbench/blob/main/0ad-junest.sh
- workflow https://github.com/ivan-hc/My-workbench/actions/workflows/0ad-junest.yml
- download https://github.com/ivan-hc/My-workbench/releases/tag/0ad

I tried to include the audio but it didn't worked. You are more expert on how 0AD works.

NOTE, if you ever decide to use my Archimage project and compile a script (based on BubbleWrap, the default), note that you need to manually change line 291 from
```
tar fx "$(find ./"$APP".AppDir -name "$APP-[0-9]*zst" | head -1)" -C ./base/
```
to
```
tar fx "$(find ./"$APP".AppDir -name "$APP"-*[0-9]*zst | grep -v data | head -1)" -C ./base/
```
since that command searches for the application archive, and there are two with the same name, `0ad` and `0ad-data` or you will get errors during compilation.

If you want to compile it using PROOT, the line is 285.

For both, the function is
```
function _extract_main_package() {
	mkdir -p base
	rm -R -f ./base/*
	tar fx "$(find ./"$APP".AppDir -name "$APP-[0-9]*zst" | head -1)" -C ./base/
	VERSION=$(cat ./base/.PKGINFO | grep pkgver | cut -c 10- | sed 's@.*:@@')
	mkdir -p deps
	rm -R -f ./deps/*
}
```
I hope my project is a good suggestion for what you want to build in the future.
